START /WAIT load_db_notifications_and_mapping
START /WAIT load_db_notifications_and_mapping
START /WAIT load_db_notifications_and_mapping
START /WAIT load_db_notifications_and_mapping
START /WAIT load_db_notifications_and_mapping